src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository", repositoryClass=QuestionRepository::class)
 */
class Question
{
  /**
   * @ORM\Id()
   * @ORM\GeneratedValue()
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $title;

  /**
   * @Gedmo\Slug(fields={"title"})
   * @ORM\Column(type="string", length=100, unique=true)
   */
  private $slug;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $questionContent;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $publishedAt;

  /**
   * @ORM\ManyToOne(targetEntity=User::class, inversedBy="questions")
   * @ORM\JoinColumn(nullable=false)
   */
  private $author;

  /**
   * @ORM\OneToMany(targetEntity="App\Entity\Answer", mappedBy="question", fetch="EXTRA_LAZY")
   * @ORM\OrderBy({"vote" = "DESC"})
   */
  private $answers;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  public function getSlug(): ?string
  {
    return $this->slug;
  }

  public function setSlug(string $slug): self
  {
    $this->slug = $slug;

    return $this;
  }

  public function getQuestionContent(): ?string
  {
    return $this->questionContent;
  }

  public function setQuestionContent(string $questionContent): self
  {
    $this->questionContent = $questionContent;

    return $this;
  }

  public function getPublishedAt(): ?\DateTimeInterface
  {
    return $this->publishedAt;
  }

  public function setPublishedAt(?\DateTimeInterface $publishedAt): self
  {
    $this->publishedAt = $publishedAt;

    return $this;
  }

  public function getAuthor(): ?User
  {
    return $this->author;
  }

  public function setAuthor(?User $author): self
  {
    $this->author = $author;

    return $this;
  }

  public function getAnswers(): Collection
  {
    return $this->answers;
  }

  public function getNonDeletedAnswers(): Collection
  {
    $criteria = QuestionRepository::createNonDeletedCriteria();

    return $this->answers->matching($criteria);
  }

  public function addAnswer(Answer $answer): self
  {
    if (!$this->answers->contains($answer)) {
      $this->answers[] = $answer;
      $answer->setQuestion($this);
    }

    return $this;
  }

  public function removeAnswer(Answer $answer): self
  {
    if ($this->answers->contains($answer)) {
      $this->answers->removeElement($answer);
      // set the owning side to null (unless already changed)
      if ($answer->getQuestion() === $this) {
        $answer->setQuestion(null);
      }
    }

    return $this;
  }
}

src/Controller/QuestionController.php
<?php

/**
 * File holding QuestionController class
 *
 * @since
 * @package App\Controller
 */

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Question;
use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * QuestionController class
 *
 * @since
 * @package App\Controller
 */
class QuestionController extends AbstractController
{
  private $logger;

  private $isDebug;

  public function __construct(LoggerInterface $logger, bool $isDebug)
  {
    $this->logger = $logger;
    $this->isDebug = $isDebug;
  }

  /**
   * @Route("/", name="app_homepage")
   */
  public function homepage(QuestionRepository $questionRepository, AnswerRepository $answerRepository)
  {
    /**
     * Example using a service.
     *
     * You need to add Environment $twigEnvironment as the method argument
     *
     * $html = $twigEnvironment->render('question/homepage.html.twig');
     *
     * return new Response($html);
     */

    $questions = $questionRepository->findAll();

    $answersNumberData = $answerRepository->findNumberOfAnswersForQuestions();
    dump($answersNumberData);
    $answersNumber = [];

    foreach ($answersNumberData as $answersNumberSingle) {
      $answersNumber[$answersNumberSingle['question_id']] = $answersNumberSingle['answer_number'];
    }

    return $this->render('question/homepage.html.twig', [
      'questions' => $questions,
      'answerData' => $answersNumber,
    ]);

  }

  /**
   * @Route("/questions/{slug}", name="app_question_show")
   */
  public function show(Question $question)
  {
    if ($this->isDebug) {
      $this->logger->info('We are in debug mode');
    }

    $answers = $question->getAnswers();

    return $this->render('question/show.html.twig', [
      'question' => $question,
      'answers'  => $answers,
    ]);
  }
}

templates/question/homepage.html.twig
{% extends 'content_base.html.twig' %}

{% block content_body %}
    <div class="bg-gradient-br-red-blue text-3xl p-20 text-white font-bold mb-4">
        <div class="container">
            <h1>Your Questions Answered</h1>
            <p class="text-lg">And even answers for those questions you didn't think to ask!</p>
        </div>
    </div>
    <div class="container">
        <div class="row mb-3">
            <div class="col">
                <button class="transition-text transition-border ease-in-out duration-300 text-sm px-4 py-2 border rounded text-gray bg-transparent border-indigo-500 text-indigo-500 hover:border-indigo-700 hover:bg-indigo-700 hover:text-white mt-4 lg:mt-0">
                    Ask a Question
                </button>
            </div>
        </div>
        <div class="row">
            {% for question in questions %}
                <div class="mb-5 shadow-sm">
                    <div class="bg-gray-200 p-4">
                        <div class="row">
                            <div class="mb-5 text-center">
                                <img src="{{ asset('images/tisha.png') }}" width="100" height="100">
                            </div>
                            <div class="col">
                                <a class="text-xl uppercase mb-5 block"
                                   href="{{ path('app_question_show', { slug: question.slug }) }}"><h2>
                                        {{ question.title }}</h2></a>
                                <div class="q-display p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"
                                         data-prefix="fas" data-icon="quote-left" class="inline-block" width="16"
                                         height="16" role="img" viewBox="0 0 512 512">
                                        <path fill="currentColor"
                                              d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z"/>
                                    </svg>
                                    <p class="d-inline">{{ question.questionContent }}</p>
                                    <p class="pt-4"><strong>{{ question.author.name }}</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="answer-link text-white" href="{{ path('app_question_show', { slug: question.slug }) }}">
                        <p class="bg-blue-800 text-center p-3">
                            <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"
                                 data-prefix="fas" data-icon="magic" class="inline-block" width="16" height="16"
                                 role="img" viewBox="0 0 512 512">
                                <path fill="currentColor"
                                      d="M224 96l16-32 32-16-32-16-16-32-16 32-32 16 32 16 16 32zM80 160l26.66-53.33L160 80l-53.34-26.67L80 0 53.34 53.33 0 80l53.34 26.67L80 160zm352 128l-26.66 53.33L352 368l53.34 26.67L432 448l26.66-53.33L512 368l-53.34-26.67L432 288zm70.62-193.77L417.77 9.38C411.53 3.12 403.34 0 395.15 0c-8.19 0-16.38 3.12-22.63 9.38L9.38 372.52c-12.5 12.5-12.5 32.76 0 45.25l84.85 84.85c6.25 6.25 14.44 9.37 22.62 9.37 8.19 0 16.38-3.12 22.63-9.37l363.14-363.15c12.5-12.48 12.5-32.75 0-45.24zM359.45 203.46l-50.91-50.91 86.6-86.6 50.91 50.91-86.6 86.6z"/>
                            </svg>
                            {{ 'num_of_answers'|trans({'answers': answerData[question.id]}) }}
                        </p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/question/show.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Question: {{ question.title }}{% endblock %}

{% block content_body %}
<div class="p-5">
    <div class="q-container-show p-5">
        <div>
            <div class="text-center">
                <img src="{{  asset('images/tisha.png') }}" alt="Question author avatar" width="100" height="100">
            </div>
            <div class="mt-2">
                <h1 class="text-white uppercase text-lg mb-4">{{ question.title }}</h1>
                <div class="bg-white p-3">
                    <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="quote-left" class="inline-block" width="16" height="16" role="img" viewBox="0 0 512 512"><path fill="currentColor" d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z"></path></svg>
                    <p class="inline-block">{{ question.questionContent|parse_markdown }}</p>
                    <p class="pt-4"><strong>-- {{ question.author.name }}</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="flex justify-between my-4">
        <h2 class="">Answers ({{ answers|length }})</h2>
        <button class="transition-text transition-border ease-in-out duration-300 text-sm px-4 py-2 border rounded text-gray bg-transparent border-indigo-500 text-indigo-500 hover:border-indigo-700 hover:bg-indigo-700 hover:text-white mt-4 lg:mt-0">Submit an Answer</button>
    </div>

    <ul class="list-none">
        {% for answer in question.nonDeletedAnswers %}
            <li class="mb-6 p-5 border-b">
                <div class="flex">
                    <div class="mr-10 pt-2 flex flex-column flex-1">
                        <div class="mr-4">
                            <img src="{{ asset('images/tisha.png') }}" alt="Answer author avatar" width="50" height="50">
                        </div>
                        <div>
                            {{ answer.content|parse_markdown }}
                            <p class="mt-2">-- {{ answer.author.name }}</p>
                        </div>
                    </div>
                    <div class="pt-2 ml-5 js-vote-arrows ml-auto" data-id="{{ answer.id }}">
                        <a class="vote-up js-vote mr-2" data-direction="up" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="arrow-alt-circle-up" width="20" height="20" class="inline-block" role="img" viewBox="0 0 512 512"><path fill="currentColor" d="M8 256C8 119 119 8 256 8s248 111 248 248-111 248-248 248S8 393 8 256zm292 116V256h70.9c10.7 0 16.1-13 8.5-20.5L264.5 121.2c-4.7-4.7-12.2-4.7-16.9 0l-115 114.3c-7.6 7.6-2.2 20.5 8.5 20.5H212v116c0 6.6 5.4 12 12 12h64c6.6 0 12-5.4 12-12z"/></svg>
                        </a>
                        <a class="vote-down js-vote mr-2" data-direction="down" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="arrow-alt-circle-down" width="20" height="20" class="inline-block" role="img" viewBox="0 0 512 512"><path fill="currentColor" d="M504 256c0 137-111 248-248 248S8 393 8 256 119 8 256 8s248 111 248 248zM212 140v116h-70.9c-10.7 0-16.1 13-8.5 20.5l114.9 114.3c4.7 4.7 12.2 4.7 16.9 0l114.9-114.3c7.6-7.6 2.2-20.5-8.5-20.5H300V140c0-6.6-5.4-12-12-12h-64c-6.6 0-12 5.4-12 12z"/></svg>
                        </a>
                        <span class="pt-1 js-vote-total">{{ answer.vote }}</span>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <a class="transition-text transition-border ease-in-out duration-300 text-sm px-4 py-2 border rounded text-gray bg-transparent border-indigo-500 text-indigo-500 hover:border-indigo-700 hover:bg-indigo-700 hover:text-white mt-4 lg:mt-0" href="{{ path('app_homepage') }}">Back</a>
</div>
{% endblock %}