src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
  use TimestampableEntity;

  /**
   * @ORM\Id()
   * @ORM\GeneratedValue()
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $title;

  /**
   * @Gedmo\Slug(fields={"title"})
   * @ORM\Column(type="string", length=100, unique=true)
   */
  private $slug;

  /**
   * @ORM\Column(type="text", nullable=true)
   */
  private $content;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $publishedAt;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $author;

  /**
   * @ORM\Column(type="integer")
   */
  private $heartCount = 0;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $imageFilename;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  public function getSlug(): ?string
  {
    return $this->slug;
  }

  public function setSlug(string $slug): self
  {
    $this->slug = $slug;

    return $this;
  }

  public function getContent(): ?string
  {
    return $this->content;
  }

  public function setContent(?string $content): self
  {
    $this->content = $content;

    return $this;
  }

  public function getPublishedAt(): ?\DateTimeInterface
  {
    return $this->publishedAt;
  }

  public function setPublishedAt(?\DateTimeInterface $publishedAt): self
  {
    $this->publishedAt = $publishedAt;

    return $this;
  }

  public function getAuthor(): ?string
  {
    return $this->author;
  }

  public function setAuthor(string $author): self
  {
    $this->author = $author;

    return $this;
  }

  public function getHeartCount(): ?int
  {
    return $this->heartCount;
  }

  public function setHeartCount(int $heartCount): self
  {
    $this->heartCount = $heartCount;

    return $this;
  }

  public function getImageFilename(): ?string
  {
    return $this->imageFilename;
  }

  public function setImageFilename(?string $imageFilename): self
  {
    $this->imageFilename = $imageFilename;

    return $this;
  }

  public function getImagePath()
  {
    return 'images/'.$this->getImageFilename();
  }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class NewsController extends AbstractController
{
  /**
   * @Route("/news", name="news")
   */
  public function index(ArticleRepository $repository)
  {
    $articles = $repository->findAllPublishedOrderedByNewest();

    return $this->render('news/index.html.twig', [
      'controller_name' => 'NewsController',
      'articles'        => $articles,
    ]);
  }

  /**
   * @Route("/news/{slug}", name="news_article_show")
   */
  public function show(Article $article)
  {
    return $this->render('news/show.html.twig', [
      'article' => $article,
    ]);
  }
}

templates/news/index.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Hello NewsController!{% endblock %}

{% block content_body %}
    <div class="p-5">
        {% for article in articles %}
            <a href="{{ path('news_article_show', { slug: article.slug }) }}">
                <article class="mt-5 mb-10 p-10 border shadow-sm" id="{{ article.slug }}">
                    <h3 class="font-bold text-xl mb-5">{{ article.title }}</h3>
                    <div class="meta-data mb-3 block">
                        {% if article.publishedAt %}
                        <span class="text-sm mr-5 inline-block">
                            Published at: <em>{{ article.publishedAt|ago }}</em>
                        </span>
                        {% endif %}
                        <span class="text-sm mr-5 inline-block">Published by: <em>{{ article.author }}</em></span>
                        <span class="text-sm mr-5 inline-block"><span>{{ article.heartCount }}</span>
                            <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="far" data-icon="heart" class="inline-block text-red-800 ml-3 align-top" width="15" height="15" role="img" viewBox="0 0 512 512"><path fill="currentColor" d="M458.4 64.3C400.6 15.7 311.3 23 256 79.3 200.7 23 111.4 15.6 53.6 64.3-21.6 127.6-10.6 230.8 43 285.5l175.4 178.7c10 10.2 23.4 15.9 37.6 15.9 14.3 0 27.6-5.6 37.6-15.8L469 285.6c53.5-54.7 64.7-157.9-10.6-221.3zm-23.6 187.5L259.4 430.5c-2.4 2.4-4.4 2.4-6.8 0L77.2 251.8c-36.5-37.2-43.9-107.6 7.3-150.7 38.9-32.7 98.9-27.8 136.5 10.5l35 35.7 35-35.7c37.8-38.5 97.8-43.2 136.5-10.6 51.1 43.1 43.5 113.9 7.3 150.8z"/></svg>
                        </span>
                    </div>
                    <p>{{ article.content|striptags|slice(0,100)|parse_markdown }}...</p>
                </article>
            </a>
        {% endfor %}
        <a class="transition-text transition-border ease-in-out duration-300 text-sm px-4 py-2 border rounded text-gray bg-transparent border-indigo-500 text-indigo-500 hover:border-indigo-700 hover:bg-indigo-700 hover:text-white mt-4 lg:mt-0" href="{{ path('app_homepage') }}">Back</a>
    </div>
{% endblock %}

templates/news/show.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Article: {{ article.title }}{% endblock %}

{% block content_body %}
<div class="p-5">
    <h1 class="mt-10 mb-10 font-bold text-xl">{{ article.title }}</h1>
    {% if article.imageFilename %}
        <img src="{{ asset(article.imagePath) }}" alt="Article image" class="mb-5" />
    {% endif %}
    <div class="meta-data mb-3 block">
        {% if article.publishedAt %}
        <span class="text-sm mr-5 inline-block">
            Published at: <em>{{ article.publishedAt|ago }}</em>
        </span>
        {% endif %}
        <span class="text-sm mr-5 inline-block">Published by: <em>{{ article.author }}</em></span>
        <span class="text-sm mr-5 inline-block"><span>{{ article.heartCount }}</span>
            <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="far" data-icon="heart" class="inline-block text-red-800 ml-3 align-top" width="15" height="15" role="img" viewBox="0 0 512 512"><path fill="currentColor" d="M458.4 64.3C400.6 15.7 311.3 23 256 79.3 200.7 23 111.4 15.6 53.6 64.3-21.6 127.6-10.6 230.8 43 285.5l175.4 178.7c10 10.2 23.4 15.9 37.6 15.9 14.3 0 27.6-5.6 37.6-15.8L469 285.6c53.5-54.7 64.7-157.9-10.6-221.3zm-23.6 187.5L259.4 430.5c-2.4 2.4-4.4 2.4-6.8 0L77.2 251.8c-36.5-37.2-43.9-107.6 7.3-150.7 38.9-32.7 98.9-27.8 136.5 10.5l35 35.7 35-35.7c37.8-38.5 97.8-43.2 136.5-10.6 51.1 43.1 43.5 113.9 7.3 150.8z"/></svg>
        </span>
    </div>
    <main class="mb-20">{{ article.content|parse_markdown }}</main>
    <a class="transition-text transition-border ease-in-out duration-300 text-sm px-4 py-2 border rounded text-gray bg-transparent border-indigo-500 text-indigo-500 hover:border-indigo-700 hover:bg-indigo-700 hover:text-white mt-4 lg:mt-0" href="{{ path('news') }}">Back to the articles</a>
</div>
{% endblock %}